article/urls.py
from django.urls import path
from .views import *

app_name = 'article'

urlpatterns = [
    
    path('', index , name= 'index'),

    path('article/search/', search_article, name='search'), 

    path('article/<int:pk>/', single_article, name='single_article'), 

    path('article/category/<int:pk>/', categorised_article, name='categorised_article'),  

    path('article/post/', post_article, name= 'post_article'), 

    path('article/update/<int:pk>/', UpdateArticle.as_view(), name="update_article"), 
    
    path('article/delete/<int:pk>/', DeleteArticle.as_view(), name="delete_article"), 

]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('privacy_policy/', privacy_policy, name='privacy_policy'), 


    path('', include('article.urls')),   
    path('users/', include('users.urls')), 

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) 

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class Category(models.Model):

    name = models.CharField(max_length = 50)
    class Meta:
        verbose_name = 'Categorie'

    def __str__(self):
        return self.name


class Article(models.Model): 

    author = models.ForeignKey(User, on_delete=models.CASCADE,  default = 1) 

    category = models.ForeignKey(Category, on_delete = models.CASCADE, default = 1 )  

    title = models.CharField(max_length=100)

    content = models.TextField(max_length = 10000)  
    

    img = models.ImageField(upload_to='article_images/', default= 'default_img.jpg') 

    pub_date = models.DateField(auto_now= True)  

    def __str__(self) -> str:
        return self.title  
    
    def get_absolute_url(self):
        return reverse('profile') 
    
    
    

article/forms.py
from django import forms 
from django.forms import ModelForm 
from .models import Article

class BootstrapImageWidget(forms.ClearableFileInput):
    def __init__(self, attrs=None):
        default_attrs = {'class': 'form-control shadow rounded-0'} 
        if attrs:
            default_attrs.update(attrs)
        super().__init__(attrs=default_attrs) 

class ArticleForm(forms.ModelForm):

    img = forms.ImageField(label='Upload a image', widget=BootstrapImageWidget())
    class Meta:
        model = Article
        fields = ('category', 'title', 'content', 'img') 

        widgets ={
            'category' : forms.Select(attrs={'class': 'form-select shadow rounded-0','placeholder': 'Select a Category'}), 

            'title': forms.TextInput(attrs={'class': 'form-control shadow rounded-0'}),

            'content': forms.Textarea(attrs={'rows':'7', 'cols':'10','class':'form-control shadow rounded-0'}), 
        } 

    

article/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required 

from django.views.generic.edit import UpdateView, DeleteView

from django.urls import reverse_lazy

from django.core.paginator  import Paginator

# Create your views here.

#conetxt processor - category
def categories(request): 

    categories = Category.objects.all()

    return {
        'categories': categories,
    }

def search_article(request):

    if 'query' in request.GET:
        query = request.GET['query'] 
        articles = Article.objects.filter(title__icontains=query) | Article.objects.filter(content__icontains=query)

    context = {
        'articles': articles,
        'query' : query,
    } 

    return render(request, 'article/categorised_article.html', context)


def index(request):
     
    all_articles = Article.objects.all()

    paginator = Paginator(all_articles, 4)

    page_number = request.GET.get("page")

    page_obj = paginator.get_page(page_number)

    recent_articles = Article.objects.all().order_by('-pub_date')[:3] 

    context = {
        # 'articles': all_articles,

        'page_obj' : page_obj, 

        'recent_articles': recent_articles
    }

    return render(request, 'article/index.html', context) 


def single_article(request, pk):

    article = Article.objects.get(pk=pk)

    context = {
        "article": article,  
    }

    return render(request, 'article/article.html', context)


def categorised_article(request, pk):

    if pk == 0:
        articles = Article.objects.all()
        context = {
            'articles': articles, 
            'category' : 'all' 
            } 

    else:
        category = Category.objects.get(pk=pk)
        articles = Article.objects.filter(category = category).all()

        context ={
            'articles': articles,
            'category' : category, 
        }

    return render(request, 'article/categorised_article.html', context)   

@login_required
def post_article(request):  
    form = ArticleForm()
    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES)  
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            article.save()  
            return redirect('article:single_article', pk=form.instance.id) 

    context = { 
        'form' : form
    } 
    return render(request, 'article/article_form.html', context) 


class UpdateArticle(UpdateView):

    model = Article

    form_class = ArticleForm

    template_name_suffix = "_update"

class DeleteArticle(DeleteView):

    model = Article 

    success_url = reverse_lazy('profile') 

article/templates/article/article.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <h2 class='mt-4' style="width:80%;">{{article.title}}</h2> 
    <h5 class='m-2'>
        By <a class="text-decoration-none" href="{% url "author_profile" article.author.id %}">
            {{article.author}}
        </a> on {{ article.pub_date }}
    </h5> 
    <img class="my-4" style="width:60%" src="{{article.img.url}}" alt=""> 
    <article style="width: 80%;">
        {{ article.content | safe }}
    </article> 
    {% comment %} <p style="width:80%;" >{{ article.content | safe }}</p>  {% endcomment %}

</div> 
{% endblock content %} 

article/templates/article/article_confirm_delete.html
{% extends "base.html" %}



{% block content %}

<div style="height: 350px;" class="container my-5">
    <form action="" method="post">
        {% csrf_token %}
        <h2>Are you sure you want to delete this article?</h2>
        <button class="btn btn-danger" type="submit">Delete</button> 
    </form>
</div>




{% endblock content %}

article/templates/article/article_form.html
{% extends "base.html" %}


{% block content %}

<div class="container" >
    <h3 class="mx-1 my-3 fw-bold text-success">Post a article</h3> 
    <form style="width:60%;" action="" method="POST" enctype = "multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div class="">
                <div class="form-label mt-2 mx-1 fw-bold text-dark "> 
                    {{field.label}}
                </div> 
                <div class="my-2">  
                    {{field}} 
                </div>   
            </div>    
        {% endfor %}   
        <button type="submit" class='btn btn-success mx-1 my-3 rounded-0'>Submit</button>
    </form>
</div>



{% endblock content %}

article/templates/article/article_update.html
{% extends "base.html" %}


{% block content %}

<div class="container">

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %} 

        <div>
            <div class="mb-3">
                <label for="id_category" class="form-label">Category</label>
                {{ form.category }}
            </div>
            {% if form.instance.img %}
                <img src="{{ form.instance.img.url }}" style="max-width:200px; max-height:200px;" /><br>
            {% endif %}
            <div class="mb-3">
                <label for="id_img" class="form-label">Image</label>
                {{ form.img }}
            </div>
            <div class="mb-3">
                <label for="id_title" class="form-label">Title</label>
                {{ form.title }}
            </div>
            <div class="mb-3">
                <label for="id_content" class="form-label">Content</label>
                {{ form.content }}
            </div>

        </div>

        <button class="btn btn-success" type="submit">Save</button>
    </form>

</div>
{% endblock content %} 

article/templates/article/carousel.html
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false">
    <div class="carousel-indicators bg-dark w-25 m-auto">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        {% for post in article_list %}  
        <div class="carousel-item {% if forloop.first %}active{% endif %}"> 
            <a href="{% url "article:single_article" post.id %}">
                <img 
                src="{{post.img.url}}" 
                class="d-block w-100 h-100" 
                alt="...">
                <div class="carousel-caption d-none d-md-block">
                <h5 class="bg-warning text-dark">{{post.title | truncatewords:5}}</h5> 
                <p class="bg-body text-dark">{{post.content | truncatewords:14}}</p> 
                </div> 
            </a>  
        </div> 
        {% endfor %} 
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon bg-dark" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon bg-dark" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
</div> 

article/templates/article/categorised_article.html
{% extends "base.html" %}


{% block content %}

<div class="container">
    {% if query %} 
    <h4 class='my-4'> results for : {{query}} </h4> 
    {% else %}
    <h4 class='my-4'>Category : {{category}}</h4>  
    {% endif %} 
    <div class="">
        {% for article in articles %}
            <a class="row text-decoration-none text-dark my-4" href="{% url "article:single_article" article.id %}"> 
                <div class="image col-4"> 
                    <img style="width:85%" src="{{article.img.url}}" alt="">  
                </div>
                <div class="contents col-8">
                    <h5 class="text-dark">{{article.title}}</h5>
                    <h6 class="d-flex">
                        Published on {{ article.pub_date }}
                    </h6> 
                    <p>{{article.content | truncatewords:50 }}</p> 
                </div>
            </a>      
        {% endfor %}
    </div>
</div>



{% endblock content %}

article/templates/article/index.html
{% extends "base.html" %}

{% block content %}


<div class="container">
    <div id="slider" class="my-3 w-75 m-auto">
        <h2 class="mb-4">Recent articles</h2>
        <div class="">
            {% include "article/carousel.html" with article_list=recent_articles %}   
        </div>
    </div>
    <div id="all_articles" class="my-5">   
        <h2 class="my-4">All Articles</h2>
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 g-4">
            {% for article in page_obj %}
                <div class="col">
                    <div class="card shadow">
                        <img src="{{ article.img.url }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 style="height: 45px;" class="card-title text-dark">{{ article.title | truncatewords:5 }}</h5>
                            <p style="height: 80px;" class="card-text">{{ article.content | truncatewords:15 }}</p>
                            <a href="{% url 'article:single_article' article.id %}" class="float-end text-decoration-none">Read more</a>
                        </div>
                    </div>
                </div> 
            {% endfor %} 
        </div>   
        
        <!-- Pagination -->
        <div id="pagination" class="my-4 d-flex justify-content-center">
            {% if page_obj.has_previous %}
                <a class="btn btn-outline-success fw-semibold mx-2" href="?page=1">First</a> 
                <a class="btn btn-outline-success fw-semibold mx-2" href="?page={{page_obj.previous_page_number}}">Previous</a> 
            {% endif %}
            <span class="h5 my-2 fw-semibold">
            Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
            </span>
            {% if page_obj.has_next %}
                <a class="btn btn-outline-success fw-semibold mx-2" href="?page={{page_obj.next_page_number}}">Next</a>    
                <a class="btn btn-outline-success fw-semibold mx-2" href="?page={{page_obj.paginator.num_pages}}">Last</a>  
            {% endif %}
        </div>
    </div>
    
</div>

 

{% endblock content %}